### PR TITLE
Adding a notebook about panel size

### PR DESCRIPTION
**Pull request by EvgSkv**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/16)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24)

**Comment by ecancellieri** [comment]
Hi @EvgSkv, I have been asked to have a look at this notebook by Plamen and Craig. Looks great to me. If I have to suggest something it is only about the comments in the function  PrecisionError, just to make it even easier for a new reader. I would replace:

# Assuming that precision is high we approximate standard deviaion by Poisson
# standard deviaton. 
negative_count_error = numpy.sqrt(size - size * precision)
total_count = size
# This is equivalent to:
# 2 * sqrt(size - size * precision) / size =
#   2 * sqrt(1 - precision) / sqrt(size)
return 2 * negative_count_error / total_count  # 2 for 95% confidence interval.

With:
# Assuming that precision is high we approximate standard deviation by Poisson
# standard deviation, that is sqrt(mean).
negative_count = size - size * precision 
negative_count_error = numpy.sqrt( negative_count )
total_count = size
relative_negative_count_error = negative_count_error / total_count
return 2 * relative_negative_count_error  # 2 is added for 95% confidence interval.

Best,
Emiliano

**Comment by EvgSkv** [comment]
Hi @ecancellieri ,
yes, this is indeed helpful for readability!
I've updated the colab. Let me know if you have further comments.
Thank you!

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
