### PR TITLE
Create examples for LabelerEvents.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 8 unresolved discussions (waiting on @tcsnfkx and @wliue)

___
*[WORKSPACE, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwFFS31tHTQe266Ge:-MezwFFT2AFq8-0cWpRC:b-evsa0f) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/WORKSPACE#L21)):*
> ```Starlark
> protobuf_deps()
> 
> http_archive(
> ```

What do you think about adding a dep on `common-cpp` instead and then using https://github.com/world-federation-of-advertisers/common-cpp/blob/main/build/com_google_absl/repo.bzl#L23 to take a dependency on Abseil to ensure that we're using a consistent version across all repos and only need to update one place to update the version.
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwhNi0uFxMmfdzdhi:-MezwhNi0uFxMmfdzdhj:b-g3i917) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L17)):*
> ```
>     email_user_info {
>       user_id: "EMAIL_USER_01"
>       profile_version: "EMAIL_PROFILE_VERSION_01"
> ```

Can you remind me what the profile version is for?
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwsI41XUtaCCr_yIG:-MezwsI41XUtaCCr_yIH:b-f0w5iu) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L33)):*
> ```
>         city_id: 20000001
>       }
>       creation_time_usec: 2000000001
> ```

To get realistic compression sizes, can you make this a realistic value? (Proto encodes small numbers using fewer bits)
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mezwz_2Bsq7_En2pBD_:-Mezwz_2Bsq7_En2pBDa:bfhr8u) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L34)):*
> ```
>       }
>       creation_time_usec: 2000000001
>       user_id_fingerprint: 200000001
> ```

Ditto, can you sample a random 64-bit integer here? (And for other fingerprints?)
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezxSc72ynI_jol0EQ6:-MezxSc72ynI_jol0EQ7:bzbe37d) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L15)):*
> ```cpp
> // limitations under the License.
> 
> #include <fcntl.h>
> ```

What is this for?
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezyyWQ9UJ_W-kuOvxn:-MezyyWQ9UJ_W-kuOvxo:b-ssu7xi) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L24)):*
> ```cpp
> #include "src/main/proto/wfa/virtual_people/common/model.pb.h"
> 
> #define FLAGS_test_srcdir \
> ```

https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros

Please just make this a function.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-0Ie-5LZqPQs5MjuK:-MezzNeA9JuJE_uin8ml:bj2pyym) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L51)):*
> ```cpp
>         absl::StrCat(FLAGS_test_srcdir, kTestRelativeDir, filename).c_str(),
>         O_RDONLY);
>     EXPECT_GT(fd, 0);
> ```

ASSERT_GT?
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-0HNQ9iFXx4z2lsIv:-Mf-0HNQ9iFXx4z2lsIw:b-dejj76) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L54)):*
> ```cpp
>     google::protobuf::io::FileInputStream file_input(fd);
>     EXPECT_TRUE(google::protobuf::TextFormat::Parse(&file_input, &event));
>     close(fd);
> ```

I'm a little worried about a lot of unclosed file descriptors if somethign goes wrong. Can you set `file_input.SetCloseOnDelete(true);` and remove the `close(fd)` call?

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @tcsnfkx)

___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwhNi0uFxMmfdzdhi:-Mf-HYwQ3d2PBCGsSjjQ:b1b49dj) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you remind me what the profile version is for?
</blockquote></details>

  // The profile version that the profile data is extracted from.
  // For example, for daily snapshots the date string can be used
  // as the version.
  // This is intended for monitoring and debugging purposes.
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-HtnLCUeV3Nuvt5wC:-Mf-HtnLCUeV3Nuvt5wD:b3hfy1c) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L65)):*
> ```
>           age {
>             min_age: 41
>             open_age_bucket {}
> ```

We no longer use open_age_bucket and the proto field will be deleted soon. Please use max_age = 1000 for open bucket.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 9 unresolved discussions (waiting on @tcsnfkx and @wliue)

___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwhNi0uFxMmfdzdhi:-Mf-OZHgBWDC8OcKK-xp:be5ge8e) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L17)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

  // The profile version that the profile data is extracted from.
  // For example, for daily snapshots the date string can be used
  // as the version.
  // This is intended for monitoring and debugging purposes.
</blockquote></details>

Should we pick a more compact example string perhaps? Like maybe "20210719".

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 10 unresolved discussions (waiting on @tcsnfkx and @wliue)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf0BElr71tL3jAiGAFl:-Mf0BElr71tL3jAiGAFm:b-27ajh5) (no related file):*
We're clocking in at ~1.2KiB for compressing these 10 protos in Riegeli format. A single event compresses to 1/3 of that, so the marginal cost for additional events seems pretty small.

I wonder if we want to come up with a flatter, more columnar proto -- it would probably compress better. For example, we can have a list of all the user ids used in order, then a list of all the profile_versions, then a list of all the genders, etc. etc. This should compress down very very well. This seems a little complex but it could be worth it -- every byte saved here translated to significant cost savings (because of a very large ciphertext expansion).

---

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: 4 of 17 files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @wliue)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf0BElr71tL3jAiGAFl:-Mf6Zo_79uf5t9ZR5XAm:b8zzliv) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We're clocking in at ~1.2KiB for compressing these 10 protos in Riegeli format. A single event compresses to 1/3 of that, so the marginal cost for additional events seems pretty small.

I wonder if we want to come up with a flatter, more columnar proto -- it would probably compress better. For example, we can have a list of all the user ids used in order, then a list of all the profile_versions, then a list of all the genders, etc. etc. This should compress down very very well. This seems a little complex but it could be worth it -- every byte saved here translated to significant cost savings (because of a very large ciphertext expansion).
</blockquote></details>

Acknowledge.

---
___
*[WORKSPACE, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwFFS31tHTQe266Ge:-Mf6b4FLAdJmS4rLo3Xu:b-j3x7y2) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/WORKSPACE#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What do you think about adding a dep on `common-cpp` instead and then using https://github.com/world-federation-of-advertisers/common-cpp/blob/main/build/com_google_absl/repo.bzl#L23 to take a dependency on Abseil to ensure that we're using a consistent version across all repos and only need to update one place to update the version.
</blockquote></details>

Updated to use common-cpp. Do you think if it makes sense to add protobuf to common-cpp?
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwhNi0uFxMmfdzdhi:-Mf9CnhYB24miVUce1pO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we pick a more compact example string perhaps? Like maybe "20210719".
</blockquote></details>

Done.
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwsI41XUtaCCr_yIG:-Mf9Cp-n5pJVNv6H2Fed:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

To get realistic compression sizes, can you make this a realistic value? (Proto encodes small numbers using fewer bits)
</blockquote></details>

Done.
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mezwz_2Bsq7_En2pBD_:-Mf9Cpa9ApoCMGJjRXvy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto, can you sample a random 64-bit integer here? (And for other fingerprints?)
</blockquote></details>

Done.
___
*[src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-HtnLCUeV3Nuvt5wC:-Mf9Cqg037YslLv2o9gG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/main/textproto/wfa/virtual_people/examples/labeler_events_example/labeler_events_01.textproto#L65)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

We no longer use open_age_bucket and the proto field will be deleted soon. Please use max_age = 1000 for open bucket.
</blockquote></details>

Done.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezxSc72ynI_jol0EQ6:-Mf99NUZ9JipEEZXFLYl:bdg03in) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

This is to include the file reading related libraries.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezyyWQ9UJ_W-kuOvxn:-Mf9CxeV90WKHSwUaY6O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros

Please just make this a function.
</blockquote></details>

Done.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-0Ie-5LZqPQs5MjuK:-Mf9CyCw0nkd5ZIC6-K-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

ASSERT_GT?
</blockquote></details>

Done.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf-0HNQ9iFXx4z2lsIv:-Mf9Cyci0Rj7QiWmjfIP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm a little worried about a lot of unclosed file descriptors if somethign goes wrong. Can you set `file_input.SetCloseOnDelete(true);` and remove the `close(fd)` call?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 3 unresolved discussions (waiting on @tcsnfkx and @wliue)

___
*[WORKSPACE, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwFFS31tHTQe266Ge:-Mf9FeLwDjjnSN_kROjP:b-7jg95q) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/WORKSPACE#L21)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Updated to use common-cpp. Do you think if it makes sense to add protobuf to common-cpp?
</blockquote></details>

It probably makes sense to add protobuf to common-cpp at some point.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf9G14w3RkLzOSc5l7E:-Mf9G14w3RkLzOSc5l7F:bms4qnx) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/d4c3b0d13efeed57e8161a9a2ff53a63782b2e72/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L55)):*
> ```cpp
>     google::protobuf::io::FileInputStream file_input(fd);
>     EXPECT_TRUE(google::protobuf::TextFormat::Parse(&file_input, &event));
>     file_input.SetCloseOnDelete(true);
> ```

Please put this line right after `file_input` is declared

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @wliue)

___
*[WORKSPACE, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-MezwFFS31tHTQe266Ge:-Mf9lRqK1bGZep5j0CsG:b8zzliv) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/b0b50b26cacbb04fedaf13fc571ce79eeb18e000/WORKSPACE#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It probably makes sense to add protobuf to common-cpp at some point.
</blockquote></details>

Acknowledge.
___
*[src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10#-Mf9G14w3RkLzOSc5l7E:-Mf9lxd52oHmBcAB4Apw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/d4c3b0d13efeed57e8161a9a2ff53a63782b2e72/src/test/cc/wfa/virtual_people/examples/labeler_events_example/labeler_events_example_test.cc#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please put this line right after `file_input` is declared
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 17 files at r1, 12 of 13 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @wliue)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: all files reviewed, 1 unresolved discussion (waiting on @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
